repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        language: docker_image
        entry: --rm hadolint/hadolint:latest-debian hadolint
        files: ^.*Dockerfile.*$
        # DL3008: apt versions, DL3002: Last user root (n√©cessaire pour entrypoint),
        # DL3059: multiple RUN (plus lisible), DL4006: pipefail
        args: [--ignore, DL3008, --ignore, DL3002, --ignore, DL3059, --ignore, DL4006]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: shellcheck
        types_or: [shell, bash, text]
        files: \.(sh|bash)$|^entrypoint\.sh$|^start_docker\.bash$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: ['--ignore-words-list', 'ament,franka,robotics,astroid']
